export const API_ERROR_CODES = [
  'VALIDATION_FAILED',
  'NOT_AUTHENTICATED',
  'FORBIDDEN',
  'NOT_FOUND',
  'ASSET_NOT_FOUND',
  'REVISION_CONFLICT',
  'STORAGE_LIMIT_EXCEEDED',
  'BUILD_DISPATCH_FAILED',
  'BUILD_FAILED',
  'SYNC_CONFLICT',
  'INTERNAL_ERROR',
] as const;

export type ApiErrorCode = typeof API_ERROR_CODES[number];
